config/routes.rb
Parovozzz::Application.routes.draw do
  root to: 'static_pages#home'
	match '/about', to: 'static_pages#about'
  match '/music', to: 'static_pages#music'
  match '/video', to: 'static_pages#video'	
	match '/news', to: 'static_pages#news'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def music
  end

  def video
  end
	
	def news
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Parovozzz"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
	  <p> Monkey Testing </p>
	</small>
	<nav>
		<ul>
			<li><%= link_to "News",		news_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="center">
	<%= link_to image_tag("parovoz.jpg", alt: "parovoz"), root_path %>
	<!--%= link_to "\app\views\static_pages\parovoz.jpg", root_path, id: "logo" %-->
		<nav>
			<%= link_to "Home",		root_path %> |
			<%= link_to "News",		news_path %> |
			<%= link_to "Video",  video_path %> |
			<%= link_to "About",	about_path %>
		</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
  <h1 align="center">
    О нас
  </h1>
  <h2 align="center">
    <small>
	  сегодня в номере
	</small>
  </h2>
  <p align="center">
    <ol start="3">
      <li>
        Сборная России, напрямую вышедшая на чемпионат мира в Бразилию,
      </li>
      <li>
        в ноябре проведёт товарищеские матчи.
          <br>
        Россияне 
      </li>
      намереваются сыграть 15 и 19 ноября — в дни проведения стыковых матчей.
        <br>
      <li>
        По данным газеты "Советский спорт", у Российского футбольного союза есть несколько вариантов.
      </li>
	  Ранее сообщалось,
	    <br>
      что россияне могут сыграть с Испанией. Также в потенциальных соперниках фигурируют сборные Бельгии и Швейцарии. Кроме того, возможен спарринг со сборной Северной Кореи. Ещё одним потенциальным соперником является сборная Молдавии.
    </ol>
  </p>
  <p align="center">
    Нападающий сине-бело-голубых Александр Кержаков стал лучшим бомбардиром в составе национальной сборной России по итогам отборочного раунда чемпионата мира 2014 года.
      <blockquote>
	    <em>
		Форвард принял участие во всех десяти матчах цикла и отличился в них пять раз. По четыре гола забили в квалификации полузащитник «Зенита» Виктор Файзулин и форвард «Динамо» Александр Кокорин, три — Роман Широков, по два — Денис Глушаков из «Спартака» и Александр Самедов из «Локомотива», один — Василий Березуцкий из ЦСКА.
      </blockquote>
    <dl>
      <dt>
        Таким
      </dt>
        <dd>
	      образом, игроки сине-бело-голубых
        </dd>
    </dl>
    записали на свой счет в общей сложности больше половины голов сборной в квалификации.
    За свою карьеру Александр Кержаков провел за главную команду страны 77 матчей и отличился в них 24 раза.
  </p>
  <p align="center">
    <del>
	  Главный тренер сборной России Фабио Капелло:
	</del>
    Мы сыграли хорошо. 
      <div>
	    Ведя в счете, могли забить еще, но иногда нам мешал вратарь соперника, а периодически не хватало толики везения.
      </div>
    Азербайджанцы имели лишь один шанс для взятия ворот и воспользовались им по максимуму. Не могу сказать, что мы недооценили оппонентов или были расслаблены. Вообще, я остался доволен отборочным циклом. Рад, что заняли первое место в группе, опередив Португалию. Эта кампания получилась сложной. "Нам нужно поработать над концентрацией, чтобы не теряться на последних минутах".
  </p>
  <a href="http://www.google.ru" target="zzz">Поищи новости сам</a>
    <br>
  <a href="video">Позырить сюда</a>
    <br>
  <table align="center" cols="2">
    <caption aligh="center">ВОТ ЭТО ПОВРОТ
	</caption>
      <tr>
	    <td>
	      пизда
        </td>
	    <td>
	      головожопа минога
        </td>
      </tr>
	  <tr>
	    <td>
	      абфрвалог
	    </td>
	  </tr>
  </table>

app/views/static_pages/afisha.html.erb
<% provide(:title, 'Afisha') %>
  <h1 align="center">
    afisha
  </h1>
  <h2 align="center">
    <small>
	  сегодня в номере
	</small>
  </h2>
  <p align="center">
    <ol start="3">
      <li>
        Сборная России, напрямую вышедшая на чемпионат мира в Бразилию,
      </li>
      <li>
        в ноябре проведёт товарищеские матчи.
          <br>
        Россияне 
      </li>
      намереваются сыграть 15 и 19 ноября — в дни проведения стыковых матчей.
        <br>
      <li>
        По данным газеты "Советский спорт", у Российского футбольного союза есть несколько вариантов.
      </li>
	  Ранее сообщалось,
	    <br>
      что россияне могут сыграть с Испанией. Также в потенциальных соперниках фигурируют сборные Бельгии и Швейцарии. Кроме того, возможен спарринг со сборной Северной Кореи. Ещё одним потенциальным соперником является сборная Молдавии.
    </ol>
  </p>
  <p align="center">
    Нападающий сине-бело-голубых Александр Кержаков стал лучшим бомбардиром в составе национальной сборной России по итогам отборочного раунда чемпионата мира 2014 года.
      <blockquote>
	    <em>
		Форвард принял участие во всех десяти матчах цикла и отличился в них пять раз. По четыре гола забили в квалификации полузащитник «Зенита» Виктор Файзулин и форвард «Динамо» Александр Кокорин, три — Роман Широков, по два — Денис Глушаков из «Спартака» и Александр Самедов из «Локомотива», один — Василий Березуцкий из ЦСКА.
      </blockquote>
    <dl>
      <dt>
        Таким
      </dt>
        <dd>
	      образом, игроки сине-бело-голубых
        </dd>
    </dl>
    записали на свой счет в общей сложности больше половины голов сборной в квалификации.
    За свою карьеру Александр Кержаков провел за главную команду страны 77 матчей и отличился в них 24 раза.
  </p>
  <p align="center">
    <del>
	  Главный тренер сборной России Фабио Капелло:
	</del>
    Мы сыграли хорошо. 
      <div>
	    Ведя в счете, могли забить еще, но иногда нам мешал вратарь соперника, а периодически не хватало толики везения.
      </div>
    Азербайджанцы имели лишь один шанс для взятия ворот и воспользовались им по максимуму. Не могу сказать, что мы недооценили оппонентов или были расслаблены. Вообще, я остался доволен отборочным циклом. Рад, что заняли первое место в группе, опередив Португалию. Эта кампания получилась сложной. "Нам нужно поработать над концентрацией, чтобы не теряться на последних минутах".
  </p>
  <a href="http://www.google.ru" target="zzz">Поищи новости сам</a>
    <br>
  <a href="video">Позырить сюда</a>
    <br>
  <table align="center" cols="2">
    <caption aligh="center">ВОТ ЭТО ПОВРОТ
	</caption>
      <tr>
	    <td>
	      пизда
        </td>
	    <td>
	      головожопа минога
        </td>
      </tr>
	  <tr>
	    <td>
	      абфрвалог
	    </td>
	  </tr>
  </table>

app/views/static_pages/home.html.erb
<h1>ГЛАВНАЯ</h1>
<div class="center">
<p class="home">
<%= link_to image_tag("afisha.jpg", alt: "qwer"), 'http://google.ru' %>
3/11 - наш первый фестиваль!

Группа "Паровоз"http://vk.com/parovoz_band в качестве одного из хедлайнеров примет участие в XIII-ом международном фестивале "K!nRock'13"! http://vk.com/kinrock_fest
</p>
</div>

app/views/static_pages/music.html.erb
<h1>StaticPages#music</h1>
<p>Find me in app/views/static_pages/music.html.erb</p>

app/views/static_pages/news.html.erb
<h1>НовосТИТ</h1>
<p class="news">Игра была очень сложной. Несмотря на то что мы большую часть матча имели численное преимущество, она была равной. Мы затратили очень много сил. Я думаю, что важные факты об этом матче — это то, что мы сумели действовать сбалансированно, создали много моментов. Жаль, что не все их реализовали. Очень серьезных и опасных моментов у своих ворот мы избежали, создать сопернику действительно что-то опасное мы не позволили.
</p>
<p class="news">«Порту» здорово действовал после удаления тактически — они располагались по схеме 4-3-2 с двумя нападающими, действующими широко, не позволяли защитникам начинать атаки, прессинговали, а наши крайние игроки обороны не очень здорово поднимались. У нас есть на этой позиции сложности — Ансальди недавно перенес травму, Кришито тоже только восстановился. А нам, чтобы выходить вперед за счет контроля мяча, нужно было, чтобы защитники поднимались выше. И еще одна деталь — мы старались всегда начинать атаки комбинациями с одной стороны и продолжали на ней же. Мы не делали диагональных переводов, не переводили мяч с фланга на фланг, чтобы растянуть команду соперника, заставить ее бегать, и тем самым облегчали им жизнь. А если бы мяч ходил с фланга на фланг быстрее, то сопернику пришлось бы тяжелее. Но у нас это не получалось.
</p>
<p class="news">Вы знаете, в прошлой игре против «Аустрии» наш игрок был удален где-то на 30-й минуте первого тайма. Это была прямая красная за совершенно обычное нарушение правил. Ничего вопиющего в этом фоле не было. Даже португальские журналисты вчера спрашивали, будет ли его нам не хватать. Конечно, нам не хватало его, как не хватало и в прошлой игре. Если говорить о сегодняшнем удалении, то первая желтая была показана за нарушение на грани между желтой и красной, потому что Халк убегал к воротам «Порту». Да, был и еще один игрок соперника, который уже бежал параллельно, мог его догнать. По-моему, Мангала, центральный защитник. Но в любом случае это была справедливая карточка. И тут же был назначен штрафной, во время которого игрок, только что получивший предупреждение, до удара вышел из стенки на 3–4 метра, и мяч попал в него. Тяжело говорить об этом эпизоде иначе, это даже не нужно. Если бы судья не показал вторую желтую, тогда бы можно было обсуждать его ошибку. Но он карточку показал, и, думаю, сделал все правильно, поэтому комментировать тут нечего.
</p>
<p class="news">Халк очень сильно провел этот матч, он был одним из основополагающих игроков. Он здорово действовал, когда смещался на правый фланг, практически всегда обыгрывал оппонента один в один, сделал голевую передачу. Халк — великолепный футболист, который был очень важен для сегодняшней победы. Лодыгин же получил удар по голове. Сейчас доктора его еще обследуют. Пока трудно сказать, что-то конкретное.
</p>
<p class="news">Начали мы неважно. Наверное, усталость сказалась из-за плотного графика. Но во втором тайме действовали уже гораздо лучше.
</p>
<p class="news">Немножко переживали за него. Тяжелое было столкновение. В таких случаях всегда переживаешь, даже если это не наш игрок. Но Юра — настоящий мужик. Нормально отыграл и после этого столкновения.
</p>
<p class="news">Игра была очень сложной. Несмотря на то что мы большую часть матча имели численное преимущество, она была равной. Мы затратили очень много сил. Я думаю, что важные факты об этом матче — это то, что мы сумели действовать сбалансированно, создали много моментов. Жаль, что не все их реализовали. Очень серьезных и опасных моментов у своих ворот мы избежали, создать сопернику действительно что-то опасное мы не позволили.
</p>
<p class="news">«Порту» здорово действовал после удаления тактически — они располагались по схеме 4-3-2 с двумя нападающими, действующими широко, не позволяли защитникам начинать атаки, прессинговали, а наши крайние игроки обороны не очень здорово поднимались. У нас есть на этой позиции сложности — Ансальди недавно перенес травму, Кришито тоже только восстановился. А нам, чтобы выходить вперед за счет контроля мяча, нужно было, чтобы защитники поднимались выше. И еще одна деталь — мы старались всегда начинать атаки комбинациями с одной стороны и продолжали на ней же. Мы не делали диагональных переводов, не переводили мяч с фланга на фланг, чтобы растянуть команду соперника, заставить ее бегать, и тем самым облегчали им жизнь. А если бы мяч ходил с фланга на фланг быстрее, то сопернику пришлось бы тяжелее. Но у нас это не получалось.
</p>
<p class="news">Вы знаете, в прошлой игре против «Аустрии» наш игрок был удален где-то на 30-й минуте первого тайма. Это была прямая красная за совершенно обычное нарушение правил. Ничего вопиющего в этом фоле не было. Даже португальские журналисты вчера спрашивали, будет ли его нам не хватать. Конечно, нам не хватало его, как не хватало и в прошлой игре. Если говорить о сегодняшнем удалении, то первая желтая была показана за нарушение на грани между желтой и красной, потому что Халк убегал к воротам «Порту». Да, был и еще один игрок соперника, который уже бежал параллельно, мог его догнать. По-моему, Мангала, центральный защитник. Но в любом случае это была справедливая карточка. И тут же был назначен штрафной, во время которого игрок, только что получивший предупреждение, до удара вышел из стенки на 3–4 метра, и мяч попал в него. Тяжело говорить об этом эпизоде иначе, это даже не нужно. Если бы судья не показал вторую желтую, тогда бы можно было обсуждать его ошибку. Но он карточку показал, и, думаю, сделал все правильно, поэтому комментировать тут нечего.
</p>
<p class="news">Халк очень сильно провел этот матч, он был одним из основополагающих игроков. Он здорово действовал, когда смещался на правый фланг, практически всегда обыгрывал оппонента один в один, сделал голевую передачу. Халк — великолепный футболист, который был очень важен для сегодняшней победы. Лодыгин же получил удар по голове. Сейчас доктора его еще обследуют. Пока трудно сказать, что-то конкретное.
</p>
<p class="news">Начали мы неважно. Наверное, усталость сказалась из-за плотного графика. Но во втором тайме действовали уже гораздо лучше.
</p>
<p class="news">Немножко переживали за него. Тяжелое было столкновение. В таких случаях всегда переживаешь, даже если это не наш игрок. Но Юра — настоящий мужик. Нормально отыграл и после этого столкновения.
</p>

app/views/static_pages/video.html.erb
<% provide(:title, 'Video') %>
<h1>VIDEO</h1>
<li class="video">
	<iframe width="420" height="315" src="//www.youtube.com/embed/dUJyctyAqsI" frameborder="0" allowfullscreen >
	</iframe>
</li>
<li class="video">
	<iframe width="420" height="315" src="//www.youtube.com/embed/G255fHPals4" frameborder="0" allowfullscreen>
	</iframe>
</li>
<li class="video">
	<iframe width="560" height="315" src="//www.youtube.com/embed/1ocU5UmxQBU" frameborder="0" allowfullscreen>
	</iframe>
</li>